site_name: 备忘录 # 网站名称
site_url: https://gaozqi.github.io/notepad # 网站地址
site_author: GaoZQi # 网站作者

repo_name: GaoZQi/notepad # 仓库名称
repo_url: https://github.com/GaoZQi/notepad # 仓库地址

theme:
    name: "material" # 主题名称
    language: "zh" # 网站语言
    favicon: images/icon.png # 网站图标
    icon: # 网站图标
        logo: material/package-variant-closed

    features: # 特性
        - content.code.annotate # 代码注释
        - navigation.tracking # 导航栏跟踪
        - navigation.tabs # 导航栏标签
        - navigation.indexes # 导航栏索引
        - navigation.top # 导航栏顶部
        - content.code.copy # 代码复制
        - content.code.annotate # 代码注释
        - navigation.footer # 导航栏底部
        - navigation.sections
        - navigation.expand #目录展开
        - navigation.path
        - toc.follow
        - content.tooltips

    palette:
        scheme: auto

    custom_dir: docs/resources

extra_css:
    - theme/css/import.css

extra_javascript:
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - theme/js/mathjax.js
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - heti
    - glightbox:
          touchNavigation: true
          loop: false
          effect: zoom
          slide_effect: slide
          width: 100%
          height: auto
          zoomable: true
          draggable: true
          skip_classes:
              - skip-lightbox
          auto_caption: false
          caption_position: bottom
          background: white
          shadow: true
          manual: false

    - search: {}

    # - encryptcontent:
    #       password_file: "passwords.yml"
    #       reload_scripts:
    #           - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    #           - theme/js/mathjax.js
    #           - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
    #       password_button: True
    #       password_button_text: "➜"
    #       title_prefix: ""
    #       summary: "限制访问！"
    #       placeholder: "请输入口令"
    #       decryption_failure_message: "⚠ 错误！"
    #       encryption_info_message: "此内容为涉及核心代码，非基地内成员禁止访问！如需访问该网站内容，请输入正确口令。"
    #       search_index: "dynamically"
    #       encrypted_something:
    #           # md-footer__inner: [nav, class]
    #           md-nav md-nav--secondary: [nav, class]
    #           # md-nav__list: [ul, class]
    #           # md-nav__title: [lable, class]
    #           # md-nav: [nav, class]
    #           # md-sidebar__inner: [div, class]

    # - git-revision-date-localized:
    #       type: timeago
    #       custom_format: "%d. %B %Y"
    #       timezone: Asia/Shanghai
    #       locale: zh
    #       fallback_to_build_date: false

    # - git-committers:
    #       repository: GaoZQi/notepad # 仓库名称
    #       branch: main

markdown_extensions:
    - abbr # 缩写
    - pymdownx.snippets # 代码块
    - pymdownx.highlight: # 代码高亮
          anchor_linenums: true # 代码行号
    - pymdownx.inlinehilite # 行内代码高亮
    - pymdownx.superfences # 内置标题栏
    - attr_list # 属性列表
    - md_in_html
    - toc: # 目录
          # permalink: "§" # 目录链接
          toc_depth: 4 # 目录深度
    - meta # 元数据
    - def_list # 定义列表
    - attr_list # 属性列表
    - md_in_html # HTML中的Markdown
    - sane_lists # 列表
    - admonition # 警告

    - pymdownx.keys # 键盘
    - pymdownx.mark # 标记
    - pymdownx.caret # 上标
    - pymdownx.keys # 键盘
    - pymdownx.tilde # 删除线
    - pymdownx.critic # 评论

    - pymdownx.details # 详情
    - pymdownx.magiclink # 链接
    - pymdownx.blocks.html
    - tables # 表格
    - pymdownx.tabbed: # 标签
          alternate_style: true # 标签样式
    - pymdownx.tasklist: # 任务列表
          custom_checkbox: true # 自定义复选框
    - pymdownx.arithmatex: # 数学公式
          generic: true # 通用
    - pymdownx.emoji: # emoji
          emoji_index:
              !!python/name:material.extensions.emoji.twemoji # emoji索引


          emoji_generator:
              !!python/name:material.extensions.emoji.to_svg # emoji生成器


    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format

nav:
    - 首页: index.md
